app = "lookatme"
primary_region = "ams"

[deploy]
  release_command = "prisma db push --skip-generate --accept-data-loss"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

[[mounts]]
  source = "lookatme_data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpus = 1
